// Copyright (c) Chemical Language Foundation 2025.

#include "ast/base/ASTNode.h"
#include "CTranslator.h"
#include <iostream>
#include "ast/types/FloatType.h"
#include "ast/types/DoubleType.h"
#include "ast/types/VoidType.h"
#include "ast/base/TypeBuilder.h"
#include "ast/types/Float128Type.h"
#include "ast/types/LongDoubleType.h"
#include "ast/types/PointerType.h"
#include "ast/types/BoolType.h"

void CTranslator::init_type_makers() {
    type_makers[clang::BuiltinType::OCLImage1dRO] = nullptr;
    type_makers[clang::BuiltinType::OCLImage1dArrayRO] = nullptr;
    type_makers[clang::BuiltinType::OCLImage1dBufferRO] = nullptr;
    type_makers[clang::BuiltinType::OCLImage2dRO] = nullptr;
    type_makers[clang::BuiltinType::OCLImage2dArrayRO] = nullptr;
    type_makers[clang::BuiltinType::OCLImage2dDepthRO] = nullptr;
    type_makers[clang::BuiltinType::OCLImage2dArrayDepthRO] = nullptr;
    type_makers[clang::BuiltinType::OCLImage2dMSAARO] = nullptr;
    type_makers[clang::BuiltinType::OCLImage2dArrayMSAARO] = nullptr;
    type_makers[clang::BuiltinType::OCLImage2dMSAADepthRO] = nullptr;
    type_makers[clang::BuiltinType::OCLImage2dArrayMSAADepthRO] = nullptr;
    type_makers[clang::BuiltinType::OCLImage3dRO] = nullptr;
    type_makers[clang::BuiltinType::OCLImage1dWO] = nullptr;
    type_makers[clang::BuiltinType::OCLImage1dArrayWO] = nullptr;
    type_makers[clang::BuiltinType::OCLImage1dBufferWO] = nullptr;
    type_makers[clang::BuiltinType::OCLImage2dWO] = nullptr;
    type_makers[clang::BuiltinType::OCLImage2dArrayWO] = nullptr;
    type_makers[clang::BuiltinType::OCLImage2dDepthWO] = nullptr;
    type_makers[clang::BuiltinType::OCLImage2dArrayDepthWO] = nullptr;
    type_makers[clang::BuiltinType::OCLImage2dMSAAWO] = nullptr;
    type_makers[clang::BuiltinType::OCLImage2dArrayMSAAWO] = nullptr;
    type_makers[clang::BuiltinType::OCLImage2dMSAADepthWO] = nullptr;
    type_makers[clang::BuiltinType::OCLImage2dArrayMSAADepthWO] = nullptr;
    type_makers[clang::BuiltinType::OCLImage3dWO] = nullptr;
    type_makers[clang::BuiltinType::OCLImage1dRW] = nullptr;
    type_makers[clang::BuiltinType::OCLImage1dArrayRW] = nullptr;
    type_makers[clang::BuiltinType::OCLImage1dBufferRW] = nullptr;
    type_makers[clang::BuiltinType::OCLImage2dRW] = nullptr;
    type_makers[clang::BuiltinType::OCLImage2dArrayRW] = nullptr;
    type_makers[clang::BuiltinType::OCLImage2dDepthRW] = nullptr;
    type_makers[clang::BuiltinType::OCLImage2dArrayDepthRW] = nullptr;
    type_makers[clang::BuiltinType::OCLImage2dMSAARW] = nullptr;
    type_makers[clang::BuiltinType::OCLImage2dArrayMSAARW] = nullptr;
    type_makers[clang::BuiltinType::OCLImage2dMSAADepthRW] = nullptr;
    type_makers[clang::BuiltinType::OCLImage2dArrayMSAADepthRW] = nullptr;
    type_makers[clang::BuiltinType::OCLImage3dRW] = nullptr;
    type_makers[clang::BuiltinType::OCLIntelSubgroupAVCMcePayload] = nullptr;
    type_makers[clang::BuiltinType::OCLIntelSubgroupAVCImePayload] = nullptr;
    type_makers[clang::BuiltinType::OCLIntelSubgroupAVCRefPayload] = nullptr;
    type_makers[clang::BuiltinType::OCLIntelSubgroupAVCSicPayload] = nullptr;
    type_makers[clang::BuiltinType::OCLIntelSubgroupAVCMceResult] = nullptr;
    type_makers[clang::BuiltinType::OCLIntelSubgroupAVCImeResult] = nullptr;
    type_makers[clang::BuiltinType::OCLIntelSubgroupAVCRefResult] = nullptr;
    type_makers[clang::BuiltinType::OCLIntelSubgroupAVCSicResult] = nullptr;
    type_makers[clang::BuiltinType::OCLIntelSubgroupAVCImeResultSingleReferenceStreamout] = nullptr;
    type_makers[clang::BuiltinType::OCLIntelSubgroupAVCImeResultDualReferenceStreamout] = nullptr;
    type_makers[clang::BuiltinType::OCLIntelSubgroupAVCImeSingleReferenceStreamin] = nullptr;
    type_makers[clang::BuiltinType::OCLIntelSubgroupAVCImeDualReferenceStreamin] = nullptr;
    type_makers[clang::BuiltinType::SveInt8] = nullptr;
    type_makers[clang::BuiltinType::SveInt16] = nullptr;
    type_makers[clang::BuiltinType::SveInt32] = nullptr;
    type_makers[clang::BuiltinType::SveInt64] = nullptr;
    type_makers[clang::BuiltinType::SveUint8] = nullptr;
    type_makers[clang::BuiltinType::SveUint16] = nullptr;
    type_makers[clang::BuiltinType::SveUint32] = nullptr;
    type_makers[clang::BuiltinType::SveUint64] = nullptr;
    type_makers[clang::BuiltinType::SveFloat16] = nullptr;
    type_makers[clang::BuiltinType::SveFloat32] = nullptr;
    type_makers[clang::BuiltinType::SveFloat64] = nullptr;
    type_makers[clang::BuiltinType::SveBFloat16] = nullptr;
    type_makers[clang::BuiltinType::SveInt8x2] = nullptr;
    type_makers[clang::BuiltinType::SveInt16x2] = nullptr;
    type_makers[clang::BuiltinType::SveInt32x2] = nullptr;
    type_makers[clang::BuiltinType::SveInt64x2] = nullptr;
    type_makers[clang::BuiltinType::SveUint8x2] = nullptr;
    type_makers[clang::BuiltinType::SveUint16x2] = nullptr;
    type_makers[clang::BuiltinType::SveUint32x2] = nullptr;
    type_makers[clang::BuiltinType::SveUint64x2] = nullptr;
    type_makers[clang::BuiltinType::SveFloat16x2] = nullptr;
    type_makers[clang::BuiltinType::SveFloat32x2] = nullptr;
    type_makers[clang::BuiltinType::SveFloat64x2] = nullptr;
    type_makers[clang::BuiltinType::SveBFloat16x2] = nullptr;
    type_makers[clang::BuiltinType::SveInt8x3] = nullptr;
    type_makers[clang::BuiltinType::SveInt16x3] = nullptr;
    type_makers[clang::BuiltinType::SveInt32x3] = nullptr;
    type_makers[clang::BuiltinType::SveInt64x3] = nullptr;
    type_makers[clang::BuiltinType::SveUint8x3] = nullptr;
    type_makers[clang::BuiltinType::SveUint16x3] = nullptr;
    type_makers[clang::BuiltinType::SveUint32x3] = nullptr;
    type_makers[clang::BuiltinType::SveUint64x3] = nullptr;
    type_makers[clang::BuiltinType::SveFloat16x3] = nullptr;
    type_makers[clang::BuiltinType::SveFloat32x3] = nullptr;
    type_makers[clang::BuiltinType::SveFloat64x3] = nullptr;
    type_makers[clang::BuiltinType::SveBFloat16x3] = nullptr;
    type_makers[clang::BuiltinType::SveInt8x4] = nullptr;
    type_makers[clang::BuiltinType::SveInt16x4] = nullptr;
    type_makers[clang::BuiltinType::SveInt32x4] = nullptr;
    type_makers[clang::BuiltinType::SveInt64x4] = nullptr;
    type_makers[clang::BuiltinType::SveUint8x4] = nullptr;
    type_makers[clang::BuiltinType::SveUint16x4] = nullptr;
    type_makers[clang::BuiltinType::SveUint32x4] = nullptr;
    type_makers[clang::BuiltinType::SveUint64x4] = nullptr;
    type_makers[clang::BuiltinType::SveFloat16x4] = nullptr;
    type_makers[clang::BuiltinType::SveFloat32x4] = nullptr;
    type_makers[clang::BuiltinType::SveFloat64x4] = nullptr;
    type_makers[clang::BuiltinType::SveBFloat16x4] = nullptr;
    type_makers[clang::BuiltinType::SveBool] = nullptr;
    type_makers[clang::BuiltinType::SveBoolx2] = nullptr;
    type_makers[clang::BuiltinType::SveBoolx4] = nullptr;
    type_makers[clang::BuiltinType::SveCount] = nullptr;
    type_makers[clang::BuiltinType::VectorQuad] = nullptr;
    type_makers[clang::BuiltinType::VectorPair] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8mf8] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8mf4] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8mf2] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8m1] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8m2] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8m4] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8m8] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8mf8] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8mf4] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8mf2] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8m1] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8m2] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8m4] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8m8] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16mf4] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16mf2] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16m1] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16m2] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16m4] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16m8] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16mf4] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16mf2] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16m1] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16m2] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16m4] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16m8] = nullptr;
    type_makers[clang::BuiltinType::RvvInt32mf2] = nullptr;
    type_makers[clang::BuiltinType::RvvInt32m1] = nullptr;
    type_makers[clang::BuiltinType::RvvInt32m2] = nullptr;
    type_makers[clang::BuiltinType::RvvInt32m4] = nullptr;
    type_makers[clang::BuiltinType::RvvInt32m8] = nullptr;
    type_makers[clang::BuiltinType::RvvUint32mf2] = nullptr;
    type_makers[clang::BuiltinType::RvvUint32m1] = nullptr;
    type_makers[clang::BuiltinType::RvvUint32m2] = nullptr;
    type_makers[clang::BuiltinType::RvvUint32m4] = nullptr;
    type_makers[clang::BuiltinType::RvvUint32m8] = nullptr;
    type_makers[clang::BuiltinType::RvvInt64m1] = nullptr;
    type_makers[clang::BuiltinType::RvvInt64m2] = nullptr;
    type_makers[clang::BuiltinType::RvvInt64m4] = nullptr;
    type_makers[clang::BuiltinType::RvvInt64m8] = nullptr;
    type_makers[clang::BuiltinType::RvvUint64m1] = nullptr;
    type_makers[clang::BuiltinType::RvvUint64m2] = nullptr;
    type_makers[clang::BuiltinType::RvvUint64m4] = nullptr;
    type_makers[clang::BuiltinType::RvvUint64m8] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16mf4] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16mf2] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16m1] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16m2] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16m4] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16m8] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat32mf2] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat32m1] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat32m2] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat32m4] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat32m8] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat64m1] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat64m2] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat64m4] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat64m8] = nullptr;
    type_makers[clang::BuiltinType::RvvBool1] = nullptr;
    type_makers[clang::BuiltinType::RvvBool2] = nullptr;
    type_makers[clang::BuiltinType::RvvBool4] = nullptr;
    type_makers[clang::BuiltinType::RvvBool8] = nullptr;
    type_makers[clang::BuiltinType::RvvBool16] = nullptr;
    type_makers[clang::BuiltinType::RvvBool32] = nullptr;
    type_makers[clang::BuiltinType::RvvBool64] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8mf8x2] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8mf8x3] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8mf8x4] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8mf8x5] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8mf8x6] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8mf8x7] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8mf8x8] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8mf4x2] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8mf4x3] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8mf4x4] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8mf4x5] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8mf4x6] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8mf4x7] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8mf4x8] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8mf2x2] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8mf2x3] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8mf2x4] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8mf2x5] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8mf2x6] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8mf2x7] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8mf2x8] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8m1x2] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8m1x3] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8m1x4] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8m1x5] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8m1x6] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8m1x7] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8m1x8] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8m2x2] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8m2x3] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8m2x4] = nullptr;
    type_makers[clang::BuiltinType::RvvInt8m4x2] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8mf8x2] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8mf8x3] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8mf8x4] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8mf8x5] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8mf8x6] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8mf8x7] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8mf8x8] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8mf4x2] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8mf4x3] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8mf4x4] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8mf4x5] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8mf4x6] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8mf4x7] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8mf4x8] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8mf2x2] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8mf2x3] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8mf2x4] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8mf2x5] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8mf2x6] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8mf2x7] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8mf2x8] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8m1x2] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8m1x3] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8m1x4] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8m1x5] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8m1x6] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8m1x7] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8m1x8] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8m2x2] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8m2x3] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8m2x4] = nullptr;
    type_makers[clang::BuiltinType::RvvUint8m4x2] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16mf4x2] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16mf4x3] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16mf4x4] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16mf4x5] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16mf4x6] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16mf4x7] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16mf4x8] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16mf2x2] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16mf2x3] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16mf2x4] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16mf2x5] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16mf2x6] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16mf2x7] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16mf2x8] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16m1x2] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16m1x3] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16m1x4] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16m1x5] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16m1x6] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16m1x7] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16m1x8] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16m2x2] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16m2x3] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16m2x4] = nullptr;
    type_makers[clang::BuiltinType::RvvInt16m4x2] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16mf4x2] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16mf4x3] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16mf4x4] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16mf4x5] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16mf4x6] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16mf4x7] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16mf4x8] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16mf2x2] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16mf2x3] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16mf2x4] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16mf2x5] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16mf2x6] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16mf2x7] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16mf2x8] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16m1x2] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16m1x3] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16m1x4] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16m1x5] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16m1x6] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16m1x7] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16m1x8] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16m2x2] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16m2x3] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16m2x4] = nullptr;
    type_makers[clang::BuiltinType::RvvUint16m4x2] = nullptr;
    type_makers[clang::BuiltinType::RvvInt32mf2x2] = nullptr;
    type_makers[clang::BuiltinType::RvvInt32mf2x3] = nullptr;
    type_makers[clang::BuiltinType::RvvInt32mf2x4] = nullptr;
    type_makers[clang::BuiltinType::RvvInt32mf2x5] = nullptr;
    type_makers[clang::BuiltinType::RvvInt32mf2x6] = nullptr;
    type_makers[clang::BuiltinType::RvvInt32mf2x7] = nullptr;
    type_makers[clang::BuiltinType::RvvInt32mf2x8] = nullptr;
    type_makers[clang::BuiltinType::RvvInt32m1x2] = nullptr;
    type_makers[clang::BuiltinType::RvvInt32m1x3] = nullptr;
    type_makers[clang::BuiltinType::RvvInt32m1x4] = nullptr;
    type_makers[clang::BuiltinType::RvvInt32m1x5] = nullptr;
    type_makers[clang::BuiltinType::RvvInt32m1x6] = nullptr;
    type_makers[clang::BuiltinType::RvvInt32m1x7] = nullptr;
    type_makers[clang::BuiltinType::RvvInt32m1x8] = nullptr;
    type_makers[clang::BuiltinType::RvvInt32m2x2] = nullptr;
    type_makers[clang::BuiltinType::RvvInt32m2x3] = nullptr;
    type_makers[clang::BuiltinType::RvvInt32m2x4] = nullptr;
    type_makers[clang::BuiltinType::RvvInt32m4x2] = nullptr;
    type_makers[clang::BuiltinType::RvvUint32mf2x2] = nullptr;
    type_makers[clang::BuiltinType::RvvUint32mf2x3] = nullptr;
    type_makers[clang::BuiltinType::RvvUint32mf2x4] = nullptr;
    type_makers[clang::BuiltinType::RvvUint32mf2x5] = nullptr;
    type_makers[clang::BuiltinType::RvvUint32mf2x6] = nullptr;
    type_makers[clang::BuiltinType::RvvUint32mf2x7] = nullptr;
    type_makers[clang::BuiltinType::RvvUint32mf2x8] = nullptr;
    type_makers[clang::BuiltinType::RvvUint32m1x2] = nullptr;
    type_makers[clang::BuiltinType::RvvUint32m1x3] = nullptr;
    type_makers[clang::BuiltinType::RvvUint32m1x4] = nullptr;
    type_makers[clang::BuiltinType::RvvUint32m1x5] = nullptr;
    type_makers[clang::BuiltinType::RvvUint32m1x6] = nullptr;
    type_makers[clang::BuiltinType::RvvUint32m1x7] = nullptr;
    type_makers[clang::BuiltinType::RvvUint32m1x8] = nullptr;
    type_makers[clang::BuiltinType::RvvUint32m2x2] = nullptr;
    type_makers[clang::BuiltinType::RvvUint32m2x3] = nullptr;
    type_makers[clang::BuiltinType::RvvUint32m2x4] = nullptr;
    type_makers[clang::BuiltinType::RvvUint32m4x2] = nullptr;
    type_makers[clang::BuiltinType::RvvInt64m1x2] = nullptr;
    type_makers[clang::BuiltinType::RvvInt64m1x3] = nullptr;
    type_makers[clang::BuiltinType::RvvInt64m1x4] = nullptr;
    type_makers[clang::BuiltinType::RvvInt64m1x5] = nullptr;
    type_makers[clang::BuiltinType::RvvInt64m1x6] = nullptr;
    type_makers[clang::BuiltinType::RvvInt64m1x7] = nullptr;
    type_makers[clang::BuiltinType::RvvInt64m1x8] = nullptr;
    type_makers[clang::BuiltinType::RvvInt64m2x2] = nullptr;
    type_makers[clang::BuiltinType::RvvInt64m2x3] = nullptr;
    type_makers[clang::BuiltinType::RvvInt64m2x4] = nullptr;
    type_makers[clang::BuiltinType::RvvInt64m4x2] = nullptr;
    type_makers[clang::BuiltinType::RvvUint64m1x2] = nullptr;
    type_makers[clang::BuiltinType::RvvUint64m1x3] = nullptr;
    type_makers[clang::BuiltinType::RvvUint64m1x4] = nullptr;
    type_makers[clang::BuiltinType::RvvUint64m1x5] = nullptr;
    type_makers[clang::BuiltinType::RvvUint64m1x6] = nullptr;
    type_makers[clang::BuiltinType::RvvUint64m1x7] = nullptr;
    type_makers[clang::BuiltinType::RvvUint64m1x8] = nullptr;
    type_makers[clang::BuiltinType::RvvUint64m2x2] = nullptr;
    type_makers[clang::BuiltinType::RvvUint64m2x3] = nullptr;
    type_makers[clang::BuiltinType::RvvUint64m2x4] = nullptr;
    type_makers[clang::BuiltinType::RvvUint64m4x2] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16mf4x2] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16mf4x3] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16mf4x4] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16mf4x5] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16mf4x6] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16mf4x7] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16mf4x8] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16mf2x2] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16mf2x3] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16mf2x4] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16mf2x5] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16mf2x6] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16mf2x7] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16mf2x8] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16m1x2] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16m1x3] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16m1x4] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16m1x5] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16m1x6] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16m1x7] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16m1x8] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16m2x2] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16m2x3] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16m2x4] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat16m4x2] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat32mf2x2] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat32mf2x3] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat32mf2x4] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat32mf2x5] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat32mf2x6] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat32mf2x7] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat32mf2x8] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat32m1x2] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat32m1x3] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat32m1x4] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat32m1x5] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat32m1x6] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat32m1x7] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat32m1x8] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat32m2x2] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat32m2x3] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat32m2x4] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat32m4x2] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat64m1x2] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat64m1x3] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat64m1x4] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat64m1x5] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat64m1x6] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat64m1x7] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat64m1x8] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat64m2x2] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat64m2x3] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat64m2x4] = nullptr;
    type_makers[clang::BuiltinType::RvvFloat64m4x2] = nullptr;
    type_makers[clang::BuiltinType::WasmExternRef] = nullptr;
    type_makers[clang::BuiltinType::Void] = [](TypeBuilder& typeBuilder, ASTAllocator& allocator, clang::BuiltinType*, SourceLocation location) -> BaseType* {
        return typeBuilder.getVoidType();
    };
    type_makers[clang::BuiltinType::Bool] = [](TypeBuilder& typeBuilder, ASTAllocator& allocator, clang::BuiltinType*, SourceLocation location) -> BaseType* {
        return typeBuilder.getBoolType();
    };
    type_makers[clang::BuiltinType::Char_U] = nullptr;
    type_makers[clang::BuiltinType::UChar] = [](TypeBuilder& typeBuilder, ASTAllocator& allocator, clang::BuiltinType*, SourceLocation location) -> BaseType* {
        return typeBuilder.getUCharType();
    };;
    type_makers[clang::BuiltinType::WChar_U] = nullptr;
    type_makers[clang::BuiltinType::Char8] = nullptr;
    type_makers[clang::BuiltinType::Char16] = nullptr;
    type_makers[clang::BuiltinType::Char32] = nullptr;
    type_makers[clang::BuiltinType::UShort] = [](TypeBuilder& typeBuilder, ASTAllocator& allocator, clang::BuiltinType*, SourceLocation location) -> BaseType* {
        return typeBuilder.getUShortType();
    };
    type_makers[clang::BuiltinType::UInt] = [](TypeBuilder& typeBuilder, ASTAllocator& allocator, clang::BuiltinType*, SourceLocation location) -> BaseType* {
        return typeBuilder.getUIntType();
    };
    type_makers[clang::BuiltinType::ULong] = [](TypeBuilder& typeBuilder, ASTAllocator& allocator, clang::BuiltinType*, SourceLocation location) -> BaseType* {
        return typeBuilder.getULongType();
    };
    type_makers[clang::BuiltinType::ULongLong] = [](TypeBuilder& typeBuilder, ASTAllocator& allocator, clang::BuiltinType*, SourceLocation location) -> BaseType* {
        return typeBuilder.getU64Type();
    };
    type_makers[clang::BuiltinType::UInt128] = [](TypeBuilder& typeBuilder, ASTAllocator& allocator, clang::BuiltinType*, SourceLocation location) -> BaseType* {
        return typeBuilder.getUInt128Type();
    };
    type_makers[clang::BuiltinType::Char_S] = [](TypeBuilder& typeBuilder, ASTAllocator& allocator, clang::BuiltinType*, SourceLocation location) -> BaseType* {
        return typeBuilder.getCharType();
    };
    type_makers[clang::BuiltinType::SChar] = [](TypeBuilder& typeBuilder, ASTAllocator& allocator, clang::BuiltinType*, SourceLocation location) -> BaseType* {
        return typeBuilder.getCharType();
    };
    type_makers[clang::BuiltinType::WChar_S] = nullptr;
    type_makers[clang::BuiltinType::Short] = [](TypeBuilder& typeBuilder, ASTAllocator& allocator, clang::BuiltinType*, SourceLocation location) -> BaseType* {
        return typeBuilder.getShortType();
    };
    type_makers[clang::BuiltinType::Int] = [](TypeBuilder& typeBuilder, ASTAllocator& allocator, clang::BuiltinType*, SourceLocation location) -> BaseType* {
        return typeBuilder.getIntType();
    };
    type_makers[clang::BuiltinType::Long] = [](TypeBuilder& typeBuilder, ASTAllocator& allocator, clang::BuiltinType*, SourceLocation location) -> BaseType* {
        return typeBuilder.getLongType();
    };
    type_makers[clang::BuiltinType::LongLong] = [](TypeBuilder& typeBuilder, ASTAllocator& allocator, clang::BuiltinType*, SourceLocation location) -> BaseType* {
        return typeBuilder.getI64Type();
    };
    type_makers[clang::BuiltinType::Int128] = [](TypeBuilder& typeBuilder, ASTAllocator& allocator, clang::BuiltinType*, SourceLocation location) -> BaseType* {
        return typeBuilder.getInt128Type();
    };
    type_makers[clang::BuiltinType::ShortAccum] = nullptr;
    type_makers[clang::BuiltinType::Accum] = nullptr;
    type_makers[clang::BuiltinType::LongAccum] = nullptr;
    type_makers[clang::BuiltinType::UShortAccum] = nullptr;
    type_makers[clang::BuiltinType::UAccum] = nullptr;
    type_makers[clang::BuiltinType::ULongAccum] = nullptr;
    type_makers[clang::BuiltinType::ShortFract] = nullptr;
    type_makers[clang::BuiltinType::Fract] = nullptr;
    type_makers[clang::BuiltinType::LongFract] = nullptr;
    type_makers[clang::BuiltinType::UShortFract] = nullptr;
    type_makers[clang::BuiltinType::UFract] = nullptr;
    type_makers[clang::BuiltinType::ULongFract] = nullptr;
    type_makers[clang::BuiltinType::SatShortAccum] = nullptr;
    type_makers[clang::BuiltinType::SatAccum] = nullptr;
    type_makers[clang::BuiltinType::SatLongAccum] = nullptr;
    type_makers[clang::BuiltinType::SatUShortAccum] = nullptr;
    type_makers[clang::BuiltinType::SatUAccum] = nullptr;
    type_makers[clang::BuiltinType::SatULongAccum] = nullptr;
    type_makers[clang::BuiltinType::SatShortFract] = nullptr;
    type_makers[clang::BuiltinType::SatFract] = nullptr;
    type_makers[clang::BuiltinType::SatLongFract] = nullptr;
    type_makers[clang::BuiltinType::SatUShortFract] = nullptr;
    type_makers[clang::BuiltinType::SatUFract] = nullptr;
    type_makers[clang::BuiltinType::SatULongFract] = nullptr;
    type_makers[clang::BuiltinType::Half] = nullptr;
    type_makers[clang::BuiltinType::Float] = [](TypeBuilder& typeBuilder, ASTAllocator& allocator, clang::BuiltinType*, SourceLocation location) -> BaseType* {
        return typeBuilder.getFloatType();
    };
    type_makers[clang::BuiltinType::Double] = [](TypeBuilder& typeBuilder, ASTAllocator& allocator, clang::BuiltinType*, SourceLocation location) -> BaseType* {
        return typeBuilder.getDoubleType();
    };
    type_makers[clang::BuiltinType::LongDouble] = [](TypeBuilder& typeBuilder, ASTAllocator& allocator, clang::BuiltinType*, SourceLocation location) -> BaseType* {
        return typeBuilder.getLongDoubleType();
    };
    type_makers[clang::BuiltinType::Float16] = nullptr;
    type_makers[clang::BuiltinType::BFloat16] = nullptr;
    type_makers[clang::BuiltinType::Float128] = [](TypeBuilder& typeBuilder, ASTAllocator& allocator, clang::BuiltinType*, SourceLocation location) -> BaseType* {
        return typeBuilder.getFloat128Type();
    };
    type_makers[clang::BuiltinType::Ibm128] = nullptr;
    type_makers[clang::BuiltinType::NullPtr] = nullptr;
    type_makers[clang::BuiltinType::ObjCId] = nullptr;
    type_makers[clang::BuiltinType::ObjCClass] = nullptr;
    type_makers[clang::BuiltinType::ObjCSel] = nullptr;
    type_makers[clang::BuiltinType::OCLSampler] = nullptr;
    type_makers[clang::BuiltinType::OCLEvent] = nullptr;
    type_makers[clang::BuiltinType::OCLClkEvent] = nullptr;
    type_makers[clang::BuiltinType::OCLQueue] = nullptr;
    type_makers[clang::BuiltinType::OCLReserveID] = nullptr;
    type_makers[clang::BuiltinType::Dependent] = nullptr;
    type_makers[clang::BuiltinType::Overload] = nullptr;
    type_makers[clang::BuiltinType::BoundMember] = nullptr;
    type_makers[clang::BuiltinType::PseudoObject] = nullptr;
    type_makers[clang::BuiltinType::UnknownAny] = nullptr;
    type_makers[clang::BuiltinType::BuiltinFn] = nullptr;
    type_makers[clang::BuiltinType::ARCUnbridgedCast] = nullptr;
    type_makers[clang::BuiltinType::IncompleteMatrixIdx] = nullptr;
    type_makers[clang::BuiltinType::OMPArraySection] = nullptr;
    type_makers[clang::BuiltinType::OMPArrayShaping] = nullptr;
    type_makers[clang::BuiltinType::OMPIterator] = nullptr;
}

void CTranslator::init_node_makers() {
    node_makers[ZigClangDeclAccessSpec] = nullptr;
    node_makers[ZigClangDeclBlock] = nullptr;
    node_makers[ZigClangDeclCaptured] = nullptr;
    node_makers[ZigClangDeclClassScopeFunctionSpecialization] = nullptr;
    node_makers[ZigClangDeclEmpty] = nullptr;
    node_makers[ZigClangDeclExport] = nullptr;
    node_makers[ZigClangDeclExternCContext] = nullptr;
    node_makers[ZigClangDeclFileScopeAsm] = nullptr;
    node_makers[ZigClangDeclFriend] = nullptr;
    node_makers[ZigClangDeclFriendTemplate] = nullptr;
    node_makers[ZigClangDeclImplicitConceptSpecialization] = nullptr;
    node_makers[ZigClangDeclImport] = nullptr;
    node_makers[ZigClangDeclLifetimeExtendedTemporary] = nullptr;
    node_makers[ZigClangDeclLinkageSpec] = nullptr;
    node_makers[ZigClangDeclUsing] = nullptr;
    node_makers[ZigClangDeclUsingEnum] = nullptr;
    node_makers[ZigClangDeclHLSLBuffer] = nullptr;
    node_makers[ZigClangDeclLabel] = nullptr;
    node_makers[ZigClangDeclNamespace] = nullptr;
    node_makers[ZigClangDeclNamespaceAlias] = nullptr;
    node_makers[ZigClangDeclObjCCompatibleAlias] = nullptr;
    node_makers[ZigClangDeclObjCCategory] = nullptr;
    node_makers[ZigClangDeclObjCCategoryImpl] = nullptr;
    node_makers[ZigClangDeclObjCImplementation] = nullptr;
    node_makers[ZigClangDeclObjCInterface] = nullptr;
    node_makers[ZigClangDeclObjCProtocol] = nullptr;
    node_makers[ZigClangDeclObjCMethod] = nullptr;
    node_makers[ZigClangDeclObjCProperty] = nullptr;
    node_makers[ZigClangDeclBuiltinTemplate] = nullptr;
    node_makers[ZigClangDeclConcept] = nullptr;
    node_makers[ZigClangDeclClassTemplate] = nullptr;
    node_makers[ZigClangDeclFunctionTemplate] = nullptr;
    node_makers[ZigClangDeclTypeAliasTemplate] = nullptr;
    node_makers[ZigClangDeclVarTemplate] = nullptr;
    node_makers[ZigClangDeclTemplateTemplateParm] = nullptr;
    node_makers[ZigClangDeclEnum] = [](CTranslator* translator, clang::Decl* decl) -> ASTNode* {
        return (ASTNode*) translator->make_enum((clang::EnumDecl*) decl);
    };
    node_makers[ZigClangDeclRecord] = [](CTranslator* translator, clang::Decl* decl) -> ASTNode* {
        return (ASTNode*) translator->make_struct((clang::RecordDecl*) decl);
    };
    node_makers[ZigClangDeclCXXRecord] = nullptr;
    node_makers[ZigClangDeclClassTemplateSpecialization] = nullptr;
    node_makers[ZigClangDeclClassTemplatePartialSpecialization] = nullptr;
    node_makers[ZigClangDeclTemplateTypeParm] = nullptr;
    node_makers[ZigClangDeclObjCTypeParam] = nullptr;
    node_makers[ZigClangDeclTypeAlias] = nullptr;
    node_makers[ZigClangDeclTypedef] = [](CTranslator* translator, clang::Decl* decl) -> ASTNode* {
        return (ASTNode*) translator->make_typealias((clang::TypedefDecl*) decl);
    };
    node_makers[ZigClangDeclUnresolvedUsingTypename] = nullptr;
    node_makers[ZigClangDeclUnresolvedUsingIfExists] = nullptr;
    node_makers[ZigClangDeclUsingDirective] = nullptr;
    node_makers[ZigClangDeclUsingPack] = nullptr;
    node_makers[ZigClangDeclUsingShadow] = nullptr;
    node_makers[ZigClangDeclConstructorUsingShadow] = nullptr;
    node_makers[ZigClangDeclBinding] = nullptr;
    node_makers[ZigClangDeclField] = nullptr;
    node_makers[ZigClangDeclObjCAtDefsField] = nullptr;
    node_makers[ZigClangDeclObjCIvar] = nullptr;
    node_makers[ZigClangDeclFunction] = [](CTranslator* translator, clang::Decl* decl) -> ASTNode* {
        return (ASTNode*) translator->make_func((clang::FunctionDecl*) decl);
    };
    node_makers[ZigClangDeclCXXDeductionGuide] = nullptr;
    node_makers[ZigClangDeclCXXMethod] = nullptr;
    node_makers[ZigClangDeclCXXConstructor] = nullptr;
    node_makers[ZigClangDeclCXXConversion] = nullptr;
    node_makers[ZigClangDeclCXXDestructor] = nullptr;
    node_makers[ZigClangDeclMSProperty] = nullptr;
    node_makers[ZigClangDeclNonTypeTemplateParm] = nullptr;
    node_makers[ZigClangDeclVar] = [](CTranslator* translator, clang::Decl* decl) -> ASTNode* {
        return (ASTNode*) translator->make_var_init((clang::VarDecl*) decl);
    };
    node_makers[ZigClangDeclDecomposition] = nullptr;
    node_makers[ZigClangDeclImplicitParam] = nullptr;
    node_makers[ZigClangDeclOMPCapturedExpr] = nullptr;
    node_makers[ZigClangDeclParmVar] = nullptr;
    node_makers[ZigClangDeclVarTemplateSpecialization] = nullptr;
    node_makers[ZigClangDeclVarTemplatePartialSpecialization] = nullptr;
    node_makers[ZigClangDeclEnumConstant] = nullptr;
    node_makers[ZigClangDeclIndirectField] = nullptr;
    node_makers[ZigClangDeclMSGuid] = nullptr;
    node_makers[ZigClangDeclOMPDeclareMapper] = nullptr;
    node_makers[ZigClangDeclOMPDeclareReduction] = nullptr;
    node_makers[ZigClangDeclTemplateParamObject] = nullptr;
    node_makers[ZigClangDeclUnnamedGlobalConstant] = nullptr;
    node_makers[ZigClangDeclUnresolvedUsingValue] = nullptr;
    node_makers[ZigClangDeclOMPAllocate] = nullptr;
    node_makers[ZigClangDeclOMPRequires] = nullptr;
    node_makers[ZigClangDeclOMPThreadPrivate] = nullptr;
    node_makers[ZigClangDeclObjCPropertyImpl] = nullptr;
    node_makers[ZigClangDeclPragmaComment] = nullptr;
    node_makers[ZigClangDeclPragmaDetectMismatch] = nullptr;
    node_makers[ZigClangDeclRequiresExprBody] = nullptr;
    node_makers[ZigClangDeclStaticAssert] = nullptr;
    node_makers[ZigClangDeclTopLevelStmt] = nullptr;
    node_makers[ZigClangDeclTranslationUnit] = nullptr;
}

void CTranslator::module_begin() {
    declared_in_module.clear();
}

void CTranslator::error(const std::string& err) {
// this can be turned on if exceptions are occurring and there's no output in console
#ifdef DEBUG
    std::cerr << "[CTranslator] Debug error :" << err << std::endl;
#endif
    diagnostics.emplace_back(
        Range { Position { 0, 0 }, Position { 0, 0 } },
        DiagSeverity::Error,
        std::nullopt,
        err
    );
}