// Copyright (c) Chemical Language Foundation 2025.

#pragma once

#include "ast/base/LoopASTNode.h"
#include "ast/base/Value.h"
#include "Scope.h"

/**
 * loop block represents the Loop Block
 *
 * loop { } <-- which repeats infinitely until stopped by
 * a break statement, the code generated by a loop block is very concise
 *
 */
class LoopBlock : public LoopASTNode, public Value {
public:

    Value* first_broken = nullptr;

    /**
     * constructor
     */
    constexpr LoopBlock(
            ASTNode* parent_node,
            SourceLocation location
    ) : LoopASTNode(ASTNodeKind::LoopBlock, parent_node, location), Value(ValueKind::LoopValue, location) {

    }

    bool link(SymbolResolver &linker, Value* &value_ptr, BaseType *expected_type = nullptr) final;

    Value* get_first_broken();

    BaseType* create_type(ASTAllocator& allocator) final;

    BaseType* known_type() final;

#ifdef COMPILER_BUILD

    llvm::Type* llvm_type(Codegen &gen) final;

    llvm::Value* llvm_value(Codegen &gen, BaseType *type = nullptr) final;

    void llvm_assign_value(Codegen &gen, llvm::Value *lhsPtr, Value *lhs) final;

    llvm::AllocaInst* llvm_allocate(Codegen &gen, const std::string &identifier, BaseType *expected_type) final;

    void code_gen(Codegen &gen) final;

#endif

};