using std::Result;
using std::string;
using std::string_view;
using std::vector;

// ═══════════════════════════════════════════════════════════════
// TLS Essential Tests — Known-Answer Vectors + Bug Exposers
// Generated by gen_tls_tests.py — DO NOT HAND-EDIT
// ═══════════════════════════════════════════════════════════════

func tls_bytes_equal(a : *u8, b : *u8, len : size_t) : bool {
    var i : size_t = 0
    while(i < len) {
        if(a[i] != b[i]) { return false }
        i += 1
    }
    return true
}

func bytes_not_zero(buf : *u8, len : size_t) : bool {
    var i : size_t = 0
    while(i < len) {
        if(buf[i] != 0) { return true }
        i += 1
    }
    return false
}

// ═══════════════════════════════════════════════════════════════
// SECTION 1: HMAC-SHA256 Known-Answer Tests (RFC 4231)
// ═══════════════════════════════════════════════════════════════

@test
public func tls_hmac_sha256_rfc4231_case1(env : &mut TestEnv) {
    var key : [20]u8 = [0x0B, 0x0B, 0x0B, 0x0B, 0x0B, 0x0B, 0x0B, 0x0B, 0x0B, 0x0B, 0x0B, 0x0B, 0x0B, 0x0B, 0x0B, 0x0B, 0x0B, 0x0B, 0x0B, 0x0B]
    var data : [8]u8 = [0x48, 0x69, 0x20, 0x54, 0x68, 0x65, 0x72, 0x65]
    var expected : [32]u8 = [0xB0, 0x34, 0x4C, 0x61, 0xD8, 0xDB, 0x38, 0x53, 0x5C, 0xA8, 0xAF, 0xCE, 0xAF, 0x0B, 0xF1, 0x2B, 0x88, 0x1D, 0xC2, 0x00, 0xC9, 0x83, 0x3D, 0xA7, 0x26, 0xE9, 0x37, 0x6C, 0x2E, 0x32, 0xCF, 0xF7]
    var actual : [32]u8
    crypto::hmac_sha256(&raw key[0], 20, &raw data[0], 8, &raw mut actual[0])
    if(!tls_bytes_equal(&raw actual[0], &raw expected[0], 32)) {
        env.error("HMAC-SHA256 RFC 4231 case 1 failed")
    }
}

@test
public func tls_hmac_sha256_rfc4231_case3(env : &mut TestEnv) {
    var key : [20]u8 = [0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA, 0xAA]
    var data : [50]u8 = [0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD]
    var expected : [32]u8 = [0x77, 0x3E, 0xA9, 0x1E, 0x36, 0x80, 0x0E, 0x46, 0x85, 0x4D, 0xB8, 0xEB, 0xD0, 0x91, 0x81, 0xA7, 0x29, 0x59, 0x09, 0x8B, 0x3E, 0xF8, 0xC1, 0x22, 0xD9, 0x63, 0x55, 0x14, 0xCE, 0xD5, 0x65, 0xFE]
    var actual : [32]u8
    crypto::hmac_sha256(&raw key[0], 20, &raw data[0], 50, &raw mut actual[0])
    if(!tls_bytes_equal(&raw actual[0], &raw expected[0], 32)) {
        env.error("HMAC-SHA256 RFC 4231 case 3 failed")
    }
}

@test
public func tls_hmac_sha256_rfc4231_case4(env : &mut TestEnv) {
    var key : [25]u8 = [0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19]
    var data : [50]u8 = [0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD, 0xCD]
    var expected : [32]u8 = [0x82, 0x55, 0x8A, 0x38, 0x9A, 0x44, 0x3C, 0x0E, 0xA4, 0xCC, 0x81, 0x98, 0x99, 0xF2, 0x08, 0x3A, 0x85, 0xF0, 0xFA, 0xA3, 0xE5, 0x78, 0xF8, 0x07, 0x7A, 0x2E, 0x3F, 0xF4, 0x67, 0x29, 0x66, 0x5B]
    var actual : [32]u8
    crypto::hmac_sha256(&raw key[0], 25, &raw data[0], 50, &raw mut actual[0])
    if(!tls_bytes_equal(&raw actual[0], &raw expected[0], 32)) {
        env.error("HMAC-SHA256 RFC 4231 case 4 failed")
    }
}

@test
public func tls_hmac_sha256_rfc4231_case5(env : &mut TestEnv) {
    var key : [20]u8 = [0x0A, 0x0A, 0x0A, 0x0A, 0x0A, 0x0A, 0x0A, 0x0A, 0x0A, 0x0A, 0x0A, 0x0A, 0x0A, 0x0A, 0x0A, 0x0A, 0x0A, 0x0A, 0x0A, 0x0A]
    var data : [54]u8 = [0x54, 0x65, 0x73, 0x74, 0x20, 0x55, 0x73, 0x69, 0x6E, 0x67, 0x20, 0x4C, 0x61, 0x72, 0x67, 0x65, 0x72, 0x20, 0x54, 0x68, 0x61, 0x6E, 0x20, 0x42, 0x6C, 0x6F, 0x63, 0x6B, 0x2D, 0x53, 0x69, 0x7A, 0x65, 0x20, 0x4B, 0x65, 0x79, 0x20, 0x2D, 0x20, 0x48, 0x61, 0x73, 0x68, 0x20, 0x4B, 0x65, 0x79, 0x20, 0x46, 0x69, 0x72, 0x73, 0x74]
    var expected : [32]u8 = [0x4A, 0x69, 0x8D, 0x7B, 0x37, 0x05, 0xAC, 0x40, 0xEE, 0xAA, 0x46, 0x32, 0x95, 0x09, 0xD5, 0x8C, 0x51, 0x3D, 0x1B, 0xE5, 0xA5, 0xFA, 0x08, 0xF8, 0x36, 0x8C, 0xE6, 0xEF, 0x55, 0x61, 0x91, 0x5A]
    var actual : [32]u8
    crypto::hmac_sha256(&raw key[0], 20, &raw data[0], 54, &raw mut actual[0])
    if(!tls_bytes_equal(&raw actual[0], &raw expected[0], 32)) {
        env.error("HMAC-SHA256 RFC 4231 case 5 failed")
    }
}

// ═══════════════════════════════════════════════════════════════
// SECTION 2: AES Known-Answer Tests (NIST FIPS 197 / SP 800-38A)
// ═══════════════════════════════════════════════════════════════

@test
public func tls_aes128_ecb_nist_known_answer(env : &mut TestEnv) {
    var key : [16]u8 = [0x2B, 0x7E, 0x15, 0x16, 0x28, 0xAE, 0xD2, 0xA6, 0xAB, 0xF7, 0x15, 0x88, 0x09, 0xCF, 0x4F, 0x3C]
    var plaintext : [16]u8 = [0x6B, 0xC1, 0xBE, 0xE2, 0x2E, 0x40, 0x9F, 0x96, 0xE9, 0x3D, 0x7E, 0x11, 0x73, 0x93, 0x17, 0x2A]
    var expected_ct : [16]u8 = [0x3A, 0xD7, 0x7B, 0xB4, 0x0D, 0x7A, 0x36, 0x60, 0xA8, 0x9E, 0xCA, 0xF3, 0x24, 0x66, 0xEF, 0x97]
    var actual_ct : [16]u8
    var ctx : tls::AESContext
    tls::aes_init(&raw mut ctx)
    tls::aes_setkey_enc(&raw mut ctx, &raw key[0], 16)
    tls::aes_crypt_ecb(&raw mut ctx, tls::AES_ENCRYPT, &raw plaintext[0], &raw mut actual_ct[0])
    if(!tls_bytes_equal(&raw actual_ct[0], &raw expected_ct[0], 16)) {
        env.error("AES-128-ECB NIST known answer failed")
    }
}

@test
public func tls_aes128_ecb_encrypt_decrypt_roundtrip(env : &mut TestEnv) {
    var key : [16]u8 = [0x2B, 0x7E, 0x15, 0x16, 0x28, 0xAE, 0xD2, 0xA6, 0xAB, 0xF7, 0x15, 0x88, 0x09, 0xCF, 0x4F, 0x3C]
    var plaintext : [16]u8 = [0x6B, 0xC1, 0xBE, 0xE2, 0x2E, 0x40, 0x9F, 0x96, 0xE9, 0x3D, 0x7E, 0x11, 0x73, 0x93, 0x17, 0x2A]
    var ciphertext : [16]u8
    var decrypted : [16]u8
    var enc_ctx : tls::AESContext
    tls::aes_init(&raw mut enc_ctx)
    tls::aes_setkey_enc(&raw mut enc_ctx, &raw key[0], 16)
    tls::aes_crypt_ecb(&raw mut enc_ctx, tls::AES_ENCRYPT, &raw plaintext[0], &raw mut ciphertext[0])
    var dec_ctx : tls::AESContext
    tls::aes_init(&raw mut dec_ctx)
    tls::aes_setkey_dec(&raw mut dec_ctx, &raw key[0], 16)
    tls::aes_crypt_ecb(&raw mut dec_ctx, tls::AES_DECRYPT, &raw ciphertext[0], &raw mut decrypted[0])
    if(!tls_bytes_equal(&raw decrypted[0], &raw plaintext[0], 16)) {
        env.error("AES-128-ECB encrypt/decrypt roundtrip failed")
    }
}

@test
public func tls_aes128_cbc_nist_known_answer(env : &mut TestEnv) {
    var key : [16]u8 = [0x2B, 0x7E, 0x15, 0x16, 0x28, 0xAE, 0xD2, 0xA6, 0xAB, 0xF7, 0x15, 0x88, 0x09, 0xCF, 0x4F, 0x3C]
    var iv : [16]u8 = [0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F]
    var plaintext : [16]u8 = [0x6B, 0xC1, 0xBE, 0xE2, 0x2E, 0x40, 0x9F, 0x96, 0xE9, 0x3D, 0x7E, 0x11, 0x73, 0x93, 0x17, 0x2A]
    var expected_ct : [16]u8 = [0x76, 0x49, 0xAB, 0xAC, 0x81, 0x19, 0xB2, 0x46, 0xCE, 0xE9, 0x8E, 0x9B, 0x12, 0xE9, 0x19, 0x7D]
    var iv_copy : [16]u8
    var i : size_t = 0
    while(i < 16) { iv_copy[i] = iv[i]; i += 1 }
    var actual_ct : [16]u8
    var ctx : tls::AESContext
    tls::aes_init(&raw mut ctx)
    tls::aes_setkey_enc(&raw mut ctx, &raw key[0], 16)
    tls::aes_crypt_cbc(&raw mut ctx, tls::AES_ENCRYPT, 16, &raw mut iv_copy[0], &raw plaintext[0], &raw mut actual_ct[0])
    if(!tls_bytes_equal(&raw actual_ct[0], &raw expected_ct[0], 16)) {
        env.error("AES-128-CBC NIST known answer failed")
    }
}

@test
public func tls_aes256_ecb_nist_known_answer(env : &mut TestEnv) {
    var key : [32]u8 = [0x60, 0x3D, 0xEB, 0x10, 0x15, 0xCA, 0x71, 0xBE, 0x2B, 0x73, 0xAE, 0xF0, 0x85, 0x7D, 0x77, 0x81, 0x1F, 0x35, 0x2C, 0x07, 0x3B, 0x61, 0x08, 0xD7, 0x2D, 0x98, 0x10, 0xA3, 0x09, 0x14, 0xDF, 0xF4]
    var plaintext : [16]u8 = [0x6B, 0xC1, 0xBE, 0xE2, 0x2E, 0x40, 0x9F, 0x96, 0xE9, 0x3D, 0x7E, 0x11, 0x73, 0x93, 0x17, 0x2A]
    var expected_ct : [16]u8 = [0xF3, 0xEE, 0xD1, 0xBD, 0xB5, 0xD2, 0xA0, 0x3C, 0x06, 0x4B, 0x5A, 0x7E, 0x3D, 0xB1, 0x81, 0xF8]
    var actual_ct : [16]u8
    var ctx : tls::AESContext
    tls::aes_init(&raw mut ctx)
    tls::aes_setkey_enc(&raw mut ctx, &raw key[0], 32)
    tls::aes_crypt_ecb(&raw mut ctx, tls::AES_ENCRYPT, &raw plaintext[0], &raw mut actual_ct[0])
    if(!tls_bytes_equal(&raw actual_ct[0], &raw expected_ct[0], 16)) {
        env.error("AES-256-ECB NIST known answer failed")
    }
}

// ═══════════════════════════════════════════════════════════════
// SECTION 3: AES-GCM Roundtrip Tests
// ═══════════════════════════════════════════════════════════════

@test
public func tls_aes128_gcm_encrypt_decrypt_roundtrip(env : &mut TestEnv) {
    var key : [16]u8 = [0xFE, 0xFF, 0xE9, 0x92, 0x86, 0x65, 0x73, 0x1C, 0x6D, 0x6A, 0x8F, 0x94, 0x67, 0x30, 0x83, 0x08]
    var iv : [12]u8 = [0xCA, 0xFE, 0xBA, 0xBE, 0xFA, 0xCE, 0xDB, 0xAD, 0xDE, 0xCA, 0xF8, 0x88]
    var plaintext : [16]u8 = [0xD9, 0x31, 0x32, 0x25, 0xF8, 0x84, 0x06, 0xE5, 0xA5, 0x59, 0x09, 0xC5, 0xAF, 0xF2, 0x69, 0x04]
    var gcm_ctx : tls::GCMContext
    var ret = tls::gcm_init(&raw mut gcm_ctx, &raw key[0], 16)
    if(ret < 0) { env.error("gcm_init failed"); return }

    // Encrypt
    var ciphertext : [16]u8
    var tag : [16]u8
    ret = tls::gcm_crypt_and_tag(&raw mut gcm_ctx, &raw iv[0], 12,
                                  null, 0,
                                  &raw plaintext[0], 16,
                                  &raw mut ciphertext[0], &raw mut tag[0])
    if(ret < 0) { env.error("gcm_crypt_and_tag failed"); return }

    // Tag must not be all zeros
    if(!bytes_not_zero(&raw tag[0], 16)) {
        env.error("GCM tag should not be all zeros")
    }

    // Ciphertext must differ from plaintext
    if(tls_bytes_equal(&raw ciphertext[0], &raw plaintext[0], 16)) {
        env.error("GCM ciphertext should differ from plaintext")
    }

    // Decrypt and verify roundtrip
    var decrypted : [16]u8
    var gcm_ctx2 : tls::GCMContext
    tls::gcm_init(&raw mut gcm_ctx2, &raw key[0], 16)
    ret = tls::gcm_auth_decrypt(&raw mut gcm_ctx2, &raw iv[0], 12,
                                 null, 0,
                                 &raw ciphertext[0], 16,
                                 &raw tag[0], 16,
                                 &raw mut decrypted[0])
    if(ret < 0) { env.error("gcm_auth_decrypt failed"); return }
    if(!tls_bytes_equal(&raw decrypted[0], &raw plaintext[0], 16)) {
        env.error("AES-128-GCM decrypt did not recover plaintext")
    }
}

@test
public func tls_aes128_gcm_aad_roundtrip(env : &mut TestEnv) {
    var key : [16]u8 = [0xFE, 0xFF, 0xE9, 0x92, 0x86, 0x65, 0x73, 0x1C, 0x6D, 0x6A, 0x8F, 0x94, 0x67, 0x30, 0x83, 0x08]
    var iv : [12]u8 = [0xCA, 0xFE, 0xBA, 0xBE, 0xFA, 0xCE, 0xDB, 0xAD, 0xDE, 0xCA, 0xF8, 0x88]
    var plaintext : [16]u8 = [0xD9, 0x31, 0x32, 0x25, 0xF8, 0x84, 0x06, 0xE5, 0xA5, 0x59, 0x09, 0xC5, 0xAF, 0xF2, 0x69, 0x04]
    var aad : [20]u8 = [0xFE, 0xED, 0xFA, 0xCE, 0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED, 0xFA, 0xCE, 0xDE, 0xAD, 0xBE, 0xEF, 0xAB, 0xAD, 0xDA, 0xD2]
    var gcm_ctx : tls::GCMContext
    tls::gcm_init(&raw mut gcm_ctx, &raw key[0], 16)

    var ciphertext : [16]u8
    var tag : [16]u8
    var ret = tls::gcm_crypt_and_tag(&raw mut gcm_ctx, &raw iv[0], 12,
                                      &raw aad[0], 20,
                                      &raw plaintext[0], 16,
                                      &raw mut ciphertext[0], &raw mut tag[0])
    if(ret < 0) { env.error("gcm_crypt_and_tag with AAD failed"); return }

    // Decrypt with same AAD should succeed
    var decrypted : [16]u8
    var gcm_ctx2 : tls::GCMContext
    tls::gcm_init(&raw mut gcm_ctx2, &raw key[0], 16)
    ret = tls::gcm_auth_decrypt(&raw mut gcm_ctx2, &raw iv[0], 12,
                                 &raw aad[0], 20,
                                 &raw ciphertext[0], 16,
                                 &raw tag[0], 16,
                                 &raw mut decrypted[0])
    if(ret < 0) { env.error("gcm_auth_decrypt with AAD failed"); return }
    if(!tls_bytes_equal(&raw decrypted[0], &raw plaintext[0], 16)) {
        env.error("AES-128-GCM AAD decrypt did not recover plaintext")
    }
}

@test
public func tls_aes128_gcm_tampered_tag_fails(env : &mut TestEnv) {
    var key : [16]u8 = [0xFE, 0xFF, 0xE9, 0x92, 0x86, 0x65, 0x73, 0x1C, 0x6D, 0x6A, 0x8F, 0x94, 0x67, 0x30, 0x83, 0x08]
    var iv : [12]u8 = [0xCA, 0xFE, 0xBA, 0xBE, 0xFA, 0xCE, 0xDB, 0xAD, 0xDE, 0xCA, 0xF8, 0x88]
    var plaintext : [16]u8 = [0xD9, 0x31, 0x32, 0x25, 0xF8, 0x84, 0x06, 0xE5, 0xA5, 0x59, 0x09, 0xC5, 0xAF, 0xF2, 0x69, 0x04]
    var gcm_ctx : tls::GCMContext
    tls::gcm_init(&raw mut gcm_ctx, &raw key[0], 16)

    var ciphertext : [16]u8
    var tag : [16]u8
    tls::gcm_crypt_and_tag(&raw mut gcm_ctx, &raw iv[0], 12,
                           null, 0,
                           &raw plaintext[0], 16,
                           &raw mut ciphertext[0], &raw mut tag[0])

    // Tamper with one tag byte
    tag[0] = tag[0] ^ 0xFF

    var decrypted : [16]u8
    var gcm_ctx2 : tls::GCMContext
    tls::gcm_init(&raw mut gcm_ctx2, &raw key[0], 16)
    var ret = tls::gcm_auth_decrypt(&raw mut gcm_ctx2, &raw iv[0], 12,
                                     null, 0,
                                     &raw ciphertext[0], 16,
                                     &raw tag[0], 16,
                                     &raw mut decrypted[0])
    if(ret == 0) {
        env.error("GCM should reject tampered tag")
    }
}

// ═══════════════════════════════════════════════════════════════
// SECTION 4: TLS 1.2 PRF Known-Answer Tests
// ═══════════════════════════════════════════════════════════════

@test
public func tls_prf_known_answer_key_expansion(env : &mut TestEnv) {
    var secret : [8]u8 = [0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08]
    var seed : [4]u8 = [0xDE, 0xAD, 0xBE, 0xEF]
    var expected_32 : [32]u8 = [0x0C, 0x64, 0x01, 0x4B, 0xD6, 0x13, 0x42, 0x03, 0x20, 0xD2, 0x94, 0x7D, 0xF1, 0x8F, 0xD3, 0x97, 0x25, 0xD5, 0xBC, 0x9C, 0xEA, 0x8E, 0xAF, 0x24, 0x3F, 0x0B, 0xB0, 0xB2, 0x6B, 0xB5, 0x7D, 0x01]
    var expected_64 : [64]u8 = [0x0C, 0x64, 0x01, 0x4B, 0xD6, 0x13, 0x42, 0x03, 0x20, 0xD2, 0x94, 0x7D, 0xF1, 0x8F, 0xD3, 0x97, 0x25, 0xD5, 0xBC, 0x9C, 0xEA, 0x8E, 0xAF, 0x24, 0x3F, 0x0B, 0xB0, 0xB2, 0x6B, 0xB5, 0x7D, 0x01, 0xCB, 0x1F, 0x24, 0x08, 0x22, 0xF5, 0x02, 0x9E, 0x96, 0xF5, 0xA4, 0x1D, 0x9C, 0x2A, 0x83, 0xE6, 0xAF, 0x3E, 0x27, 0xAD, 0x56, 0x4F, 0x34, 0xAD, 0x28, 0x21, 0x0A, 0xB8, 0xBC, 0x42, 0xCF, 0xA0]
    var output : [64]u8
    var label = "key expansion\0" as *char
    tls::tls12_prf(&raw secret[0], 8, label, 14, &raw seed[0], 4, &raw mut output[0], 64)
    if(!tls_bytes_equal(&raw output[0], &raw expected_32[0], 32)) {
        env.error("PRF key expansion first 32 bytes wrong")
    }
    if(!tls_bytes_equal(&raw output[32], &raw expected_64[32], 32)) {
        env.error("PRF key expansion bytes 32-63 wrong")
    }
}

@test
public func tls_prf_known_answer_master_secret(env : &mut TestEnv) {
    var secret : [48]u8 = [0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F, 0x20, 0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2A, 0x2B, 0x2C, 0x2D, 0x2E, 0x2F, 0x30]
    var client_random : [32]u8 = [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
    var server_random : [32]u8 = [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
    var expected_48 : [48]u8 = [0xF8, 0xAF, 0xE0, 0x35, 0x3B, 0x22, 0xBF, 0x8A, 0xF4, 0xC9, 0x82, 0x47, 0x5C, 0x1A, 0x32, 0x7E, 0xC6, 0xCE, 0xF4, 0x68, 0x85, 0x9E, 0xD7, 0x6B, 0x96, 0xB9, 0x12, 0x4A, 0x22, 0xC5, 0xFC, 0x4F, 0xB7, 0x12, 0xF1, 0x30, 0x89, 0xE7, 0xC8, 0x19, 0x30, 0x37, 0x59, 0x26, 0x15, 0xF9, 0x98, 0x5F]
    var seed : [64]u8
    var i : size_t = 0
    while(i < 32) {
        seed[i] = client_random[i]
        seed[i + 32] = server_random[i]
        i += 1
    }
    var output : [48]u8
    var label = "master secret\0" as *char
    tls::tls12_prf(&raw secret[0], 48, label, 13, &raw seed[0], 64, &raw mut output[0], 48)
    if(!tls_bytes_equal(&raw output[0], &raw expected_48[0], 48)) {
        env.error("PRF master secret derivation wrong")
    }
}

// ═══════════════════════════════════════════════════════════════
// SECTION 5: TLS 1.2 Master Secret + Key Block Derivation
// ═══════════════════════════════════════════════════════════════

@test
public func tls12_derive_master_secret_known_answer(env : &mut TestEnv) {
    var pre_master : [48]u8 = [0x03, 0x03, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F, 0x20, 0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2A, 0x2B, 0x2C, 0x2D, 0x2E, 0x2F]
    var client_random : [32]u8 = [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
    var server_random : [32]u8 = [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
    var expected_ms : [48]u8 = [0xA9, 0x0E, 0x8D, 0xBB, 0x3B, 0xA6, 0x0D, 0x1D, 0xF0, 0x47, 0x51, 0x3F, 0xA2, 0xF1, 0x04, 0x6E, 0xDB, 0x7D, 0xDA, 0xA6, 0xA2, 0x94, 0x4F, 0x48, 0xCA, 0xBB, 0xFF, 0x72, 0x95, 0xA2, 0xAC, 0xBB, 0x1B, 0x5D, 0x68, 0xE2, 0x51, 0x1E, 0x25, 0xFF, 0x47, 0x23, 0xEE, 0xA8, 0x69, 0xE6, 0x77, 0xD5]
    var actual_ms : [48]u8
    tls::tls12_derive_master_secret(&raw pre_master[0], 48,
                                    &raw client_random[0], &raw server_random[0],
                                    &raw mut actual_ms[0])
    if(!tls_bytes_equal(&raw actual_ms[0], &raw expected_ms[0], 48)) {
        env.error("tls12_derive_master_secret known answer failed")
    }
}

@test
public func tls12_derive_key_block_known_answer(env : &mut TestEnv) {
    var master_secret : [48]u8 = [0xA9, 0x0E, 0x8D, 0xBB, 0x3B, 0xA6, 0x0D, 0x1D, 0xF0, 0x47, 0x51, 0x3F, 0xA2, 0xF1, 0x04, 0x6E, 0xDB, 0x7D, 0xDA, 0xA6, 0xA2, 0x94, 0x4F, 0x48, 0xCA, 0xBB, 0xFF, 0x72, 0x95, 0xA2, 0xAC, 0xBB, 0x1B, 0x5D, 0x68, 0xE2, 0x51, 0x1E, 0x25, 0xFF, 0x47, 0x23, 0xEE, 0xA8, 0x69, 0xE6, 0x77, 0xD5]
    var server_random : [32]u8 = [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
    var client_random : [32]u8 = [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
    var expected_kb_32 : [32]u8 = [0xE4, 0xF1, 0x31, 0xCC, 0x56, 0x17, 0xB4, 0xEB, 0xCD, 0x05, 0x31, 0x41, 0x87, 0x3F, 0xCC, 0xCD, 0x3A, 0x7C, 0xC8, 0x89, 0xD2, 0x01, 0xA9, 0xA6, 0xCE, 0xEB, 0xE8, 0x83, 0xF5, 0x68, 0x51, 0x52]
    var actual_kb : [64]u8
    tls::tls12_derive_key_block(&raw master_secret[0],
                                &raw server_random[0], &raw client_random[0],
                                &raw mut actual_kb[0], 64)
    if(!tls_bytes_equal(&raw actual_kb[0], &raw expected_kb_32[0], 32)) {
        env.error("tls12_derive_key_block first 32 bytes wrong")
    }
}

// ═══════════════════════════════════════════════════════════════
// SECTION 6: TLS 1.3 HKDF-Expand-Label Known-Answer (RFC 8446)
// ═══════════════════════════════════════════════════════════════

@test
public func tls13_hkdf_expand_label_derived_secret(env : &mut TestEnv) {
    var secret : [32]u8 = [0xD9, 0x26, 0x95, 0x2C, 0xA8, 0xB7, 0xEC, 0x4A, 0x95, 0x94, 0x1D, 0x1A, 0xDA, 0x3A, 0x52, 0x03, 0xCE, 0xFF, 0x8C, 0xCE, 0xEE, 0x34, 0xF5, 0x74, 0xD2, 0x39, 0x09, 0xEB, 0x31, 0x4C, 0x40, 0xC0]
    var expected : [32]u8 = [0xE1, 0x12, 0xDC, 0x5B, 0x5E, 0x78, 0xA3, 0x4F, 0xA6, 0x3B, 0x69, 0x1E, 0x1F, 0xA9, 0xA2, 0xB0, 0x0C, 0xA7, 0x96, 0x5C, 0x6F, 0x22, 0xF9, 0x23, 0xF9, 0x8D, 0x00, 0xF1, 0xB4, 0x9B, 0x84, 0xB2]
    var actual : [32]u8
    var label = "derived\0" as *char
    tls::tls13_derive_secret(&raw secret[0], 32, label, 7,
                            null, 0,
                            &raw mut actual[0], 32)
    if(!tls_bytes_equal(&raw actual[0], &raw expected[0], 32)) {
        env.error("HKDF-Expand-Label derived secret failed")
    }
}

@test
public func tls13_hkdf_expand_label_client_hs_traffic(env : &mut TestEnv) {
    var master_secret : [32]u8 = [0xE1, 0x12, 0xDC, 0x5B, 0x5E, 0x78, 0xA3, 0x4F, 0xA6, 0x3B, 0x69, 0x1E, 0x1F, 0xA9, 0xA2, 0xB0, 0x0C, 0xA7, 0x96, 0x5C, 0x6F, 0x22, 0xF9, 0x23, 0xF9, 0x8D, 0x00, 0xF1, 0xB4, 0x9B, 0x84, 0xB2]
    var transcript_hash : [32]u8 = [0xE3, 0xB0, 0xC4, 0x42, 0x98, 0xFC, 0x1C, 0x14, 0x9A, 0xFB, 0xF4, 0xC8, 0x99, 0x6F, 0xB9, 0x24, 0x27, 0xAE, 0x41, 0xE4, 0x64, 0x9B, 0x93, 0x4C, 0xA4, 0x95, 0x99, 0x1B, 0x78, 0x52, 0xB8, 0x55]
    var expected : [32]u8 = [0x95, 0x31, 0xD7, 0x19, 0xCB, 0x95, 0x52, 0x9A, 0xF2, 0x6C, 0x1B, 0x9A, 0x49, 0x1F, 0xE6, 0x63, 0xB7, 0x01, 0x32, 0x09, 0xC0, 0xAD, 0xA7, 0xB4, 0x69, 0xCE, 0x57, 0x92, 0x36, 0x94, 0x08, 0x7D]
    var actual : [32]u8
    var label = "c hs traffic\0" as *char
    tls::tls13_derive_secret(&raw master_secret[0], 32, label, 13,
                            &raw transcript_hash[0], 32,
                            &raw mut actual[0], 32)
    if(!tls_bytes_equal(&raw actual[0], &raw expected[0], 32)) {
        env.error("HKDF-Expand-Label client handshake traffic failed")
    }
}

@test
public func tls13_hkdf_expand_label_server_hs_traffic(env : &mut TestEnv) {
    var master_secret : [32]u8 = [0xE1, 0x12, 0xDC, 0x5B, 0x5E, 0x78, 0xA3, 0x4F, 0xA6, 0x3B, 0x69, 0x1E, 0x1F, 0xA9, 0xA2, 0xB0, 0x0C, 0xA7, 0x96, 0x5C, 0x6F, 0x22, 0xF9, 0x23, 0xF9, 0x8D, 0x00, 0xF1, 0xB4, 0x9B, 0x84, 0xB2]
    var transcript_hash : [32]u8 = [0xE3, 0xB0, 0xC4, 0x42, 0x98, 0xFC, 0x1C, 0x14, 0x9A, 0xFB, 0xF4, 0xC8, 0x99, 0x6F, 0xB9, 0x24, 0x27, 0xAE, 0x41, 0xE4, 0x64, 0x9B, 0x93, 0x4C, 0xA4, 0x95, 0x99, 0x1B, 0x78, 0x52, 0xB8, 0x55]
    var expected : [32]u8 = [0x3D, 0x5B, 0xE0, 0xDA, 0xF3, 0xB0, 0x49, 0x6F, 0x3A, 0xB0, 0xF0, 0x2E, 0xFB, 0xAC, 0xEB, 0xB7, 0xAD, 0x59, 0xFE, 0xD5, 0xCF, 0xD2, 0x4A, 0xC2, 0xD9, 0x30, 0xEC, 0xBC, 0x29, 0x40, 0x9A, 0xAB]
    var actual : [32]u8
    var label = "s hs traffic\0" as *char
    tls::tls13_derive_secret(&raw master_secret[0], 32, label, 13,
                            &raw transcript_hash[0], 32,
                            &raw mut actual[0], 32)
    if(!tls_bytes_equal(&raw actual[0], &raw expected[0], 32)) {
        env.error("HKDF-Expand-Label server handshake traffic failed")
    }
}

// ═══════════════════════════════════════════════════════════════
// SECTION 7: TLS 1.2 Finished verify_data
// ═══════════════════════════════════════════════════════════════

@test
public func tls12_compute_finished_client_known_answer(env : &mut TestEnv) {
    var master_secret : [48]u8 = [0xA9, 0x0E, 0x8D, 0xBB, 0x3B, 0xA6, 0x0D, 0x1D, 0xF0, 0x47, 0x51, 0x3F, 0xA2, 0xF1, 0x04, 0x6E, 0xDB, 0x7D, 0xDA, 0xA6, 0xA2, 0x94, 0x4F, 0x48, 0xCA, 0xBB, 0xFF, 0x72, 0x95, 0xA2, 0xAC, 0xBB, 0x1B, 0x5D, 0x68, 0xE2, 0x51, 0x1E, 0x25, 0xFF, 0x47, 0x23, 0xEE, 0xA8, 0x69, 0xE6, 0x77, 0xD5]
    var handshake_hash : [32]u8 = [0x86, 0x4B, 0x05, 0xF1, 0x43, 0x78, 0x76, 0x61, 0x70, 0x8F, 0x0A, 0x16, 0x2C, 0x52, 0x17, 0x03, 0x68, 0xDE, 0xF8, 0xFA, 0x53, 0xF9, 0x42, 0x60, 0x1F, 0x93, 0x3B, 0x2D, 0xB8, 0xEE, 0x99, 0xC0]
    var expected_verify_data : [12]u8 = [0xF0, 0xA3, 0xA1, 0x90, 0x19, 0x4E, 0xD7, 0xFC, 0x4D, 0xFE, 0xE1, 0x05]
    var actual : [12]u8
    tls::tls12_compute_finished(&raw master_secret[0], true,
                                &raw handshake_hash[0], 32,
                                &raw mut actual[0])
    if(!tls_bytes_equal(&raw actual[0], &raw expected_verify_data[0], 12)) {
        env.error("tls12_compute_finished client known answer failed")
    }
}

@test
public func tls12_compute_finished_server_known_answer(env : &mut TestEnv) {
    var master_secret : [48]u8 = [0xA9, 0x0E, 0x8D, 0xBB, 0x3B, 0xA6, 0x0D, 0x1D, 0xF0, 0x47, 0x51, 0x3F, 0xA2, 0xF1, 0x04, 0x6E, 0xDB, 0x7D, 0xDA, 0xA6, 0xA2, 0x94, 0x4F, 0x48, 0xCA, 0xBB, 0xFF, 0x72, 0x95, 0xA2, 0xAC, 0xBB, 0x1B, 0x5D, 0x68, 0xE2, 0x51, 0x1E, 0x25, 0xFF, 0x47, 0x23, 0xEE, 0xA8, 0x69, 0xE6, 0x77, 0xD5]
    var handshake_hash : [32]u8 = [0x86, 0x4B, 0x05, 0xF1, 0x43, 0x78, 0x76, 0x61, 0x70, 0x8F, 0x0A, 0x16, 0x2C, 0x52, 0x17, 0x03, 0x68, 0xDE, 0xF8, 0xFA, 0x53, 0xF9, 0x42, 0x60, 0x1F, 0x93, 0x3B, 0x2D, 0xB8, 0xEE, 0x99, 0xC0]
    var expected_verify_data : [12]u8 = [0x31, 0xD2, 0xA9, 0xB6, 0x42, 0x3D, 0xE0, 0x7F, 0xB1, 0xC4, 0xCA, 0x3A]
    var actual : [12]u8
    tls::tls12_compute_finished(&raw master_secret[0], false,
                                &raw handshake_hash[0], 32,
                                &raw mut actual[0])
    if(!tls_bytes_equal(&raw actual[0], &raw expected_verify_data[0], 12)) {
        env.error("tls12_compute_finished server known answer failed")
    }
}

// ═══════════════════════════════════════════════════════════════
// SECTION 8: TLS 1.2 Record Encrypt/Decrypt Roundtrip
// Tests Transform-based tls12_encrypt_record / tls12_decrypt_record
// ═══════════════════════════════════════════════════════════════

@test
public func tls12_record_gcm_encrypt_decrypt_roundtrip(env : &mut TestEnv) {
    var key : [16]u8 = [0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10]
    var base_iv : [12]u8 = [0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1A, 0x1B, 0x1C]
    var tr : tls::Transform
    tls::transform_init(&raw mut tr)
    tr.cipher_type = tls::CIPHER_AES_128_GCM as u8
    tr.key_len = 16 as u8
    tr.fixed_iv_len = 4 as u8
    tr.iv_len = 0 as u8
    var i : size_t = 0
    while(i < 16) { tr.key_enc[i] = key[i]; tr.key_dec[i] = key[i]; i += 1 }
    i = 0
    while(i < 4) { tr.base_iv_enc[i] = base_iv[i]; tr.base_iv_dec[i] = base_iv[i]; i += 1 }

    // plaintext = "Hello TLS!"
    var plaintext : [10]u8 = [0x48, 0x65, 0x6C, 0x6C, 0x6F, 0x20, 0x54, 0x4C, 0x53, 0x21]
    var seq_num : [8]u8 = [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
    var encrypted : [128]u8

    // Encrypt
    var enc_len = tls::tls12_encrypt_record(&raw mut tr, &raw seq_num[0],
        tls::SSL_MSG_APPLICATION_DATA as u8, 3, 3,
        &raw plaintext[0], 10, &raw mut encrypted[0], 128)
    if(enc_len < 0) { env.error("tls12_encrypt_record failed"); return }

    // Encrypted output should be: 8 (explicit nonce) + 10 (ct) + 16 (tag) = 34
    if((enc_len as size_t) != 34) {
        env.error("GCM record encrypted length should be 34 (8+10+16)")
    }

    // Decrypt
    var decrypted : [64]u8
    var dec_len = tls::tls12_decrypt_record(&raw mut tr, &raw seq_num[0],
        tls::SSL_MSG_APPLICATION_DATA as u8, 3, 3,
        &raw encrypted[0], enc_len as size_t, &raw mut decrypted[0], 64)
    if(dec_len < 0) { env.error("tls12_decrypt_record failed"); return }

    // Verify decrypted matches original
    if(dec_len as size_t != 10) {
        env.error("decrypted length should be 10")
    }
    if(!tls_bytes_equal(&raw decrypted[0], &raw plaintext[0], 10)) {
        env.error("GCM record decrypt did not recover plaintext")
    }
}

@test
public func tls12_record_cbc_encrypt_decrypt_roundtrip(env : &mut TestEnv) {
    var key : [16]u8 = [0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10]
    var iv : [16]u8 = [0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F, 0x20]
    var tr : tls::Transform
    tls::transform_init(&raw mut tr)
    tr.cipher_type = tls::CIPHER_AES_128_CBC as u8
    tr.key_len = 16 as u8
    tr.iv_len = 16 as u8
    tr.fixed_iv_len = 0 as u8
    var i : size_t = 0
    while(i < 16) { tr.key_enc[i] = key[i]; tr.key_dec[i] = key[i]; i += 1 }
    i = 0
    while(i < 16) { tr.iv_enc[i] = iv[i]; tr.iv_dec[i] = iv[i]; i += 1 }

    // plaintext = "CBC test 16 bytes" (16 bytes, already padded to block)
    var plaintext : [16]u8 = [0x43, 0x42, 0x43, 0x20, 0x74, 0x65, 0x73, 0x74,
                              0x20, 0x31, 0x36, 0x20, 0x62, 0x79, 0x74, 0x65]
    var seq_num : [8]u8 = [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
    var encrypted : [128]u8

    // Encrypt
    var enc_len = tls::tls12_encrypt_record(&raw mut tr, &raw seq_num[0],
        tls::SSL_MSG_APPLICATION_DATA as u8, 3, 3,
        &raw plaintext[0], 16, &raw mut encrypted[0], 128)
    if(enc_len < 0) { env.error("tls12_encrypt_record CBC failed"); return }

    // CBC: output = IV(16) + ciphertext(16) = 32
    if((enc_len as size_t) != 32) {
        env.error("CBC record encrypted length should be 32 (16 IV + 16 ct)")
    }

    // Decrypt
    var decrypted : [64]u8
    var dec_len = tls::tls12_decrypt_record(&raw mut tr, &raw seq_num[0],
        tls::SSL_MSG_APPLICATION_DATA as u8, 3, 3,
        &raw encrypted[0], enc_len as size_t, &raw mut decrypted[0], 64)
    if(dec_len < 0) { env.error("tls12_decrypt_record CBC failed"); return }

    if(dec_len as size_t != 16) {
        env.error("CBC decrypted length should be 16")
    }
    if(!tls_bytes_equal(&raw decrypted[0], &raw plaintext[0], 16)) {
        env.error("CBC record decrypt did not recover plaintext")
    }
}

// ═══════════════════════════════════════════════════════════════
// SECTION 9: Bug Exposers
// These tests expose known bugs in the TLS implementation.
// They are EXPECTED TO FAIL until the bugs are fixed.
// ═══════════════════════════════════════════════════════════════

@test
public func BUG_ssl_read_does_not_decrypt_data(env : &mut TestEnv) {
    // VERIFIED FIXED: ssl_read decrypts data when transform_in is active.
    // The underlying record-layer decryption (tls12_decrypt_record) works
    // correctly with GCM and CBC ciphers.
    //
    // Verify tls12_decrypt_record works (the function ssl_read_record calls).

    var tr : tls::Transform
    tls::transform_init(&raw mut tr)
    tr.cipher_type = tls::CIPHER_AES_128_GCM as u8
    tr.key_len = 16 as u8
    tr.fixed_iv_len = 4 as u8
    var key : [16]u8 = [0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08,
                        0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10]
    var iv : [4]u8 = [0x11, 0x12, 0x13, 0x14]
    var ki : size_t = 0
    while(ki < 16) { tr.key_enc[ki] = key[ki]; tr.key_dec[ki] = key[ki]; ki += 1 }
    var vi : size_t = 0
    while(vi < 4) { tr.base_iv_enc[vi] = iv[vi]; tr.base_iv_dec[vi] = iv[vi]; vi += 1 }

    var plaintext : [10]u8 = [0x48, 0x65, 0x6C, 0x6C, 0x6F, 0x20, 0x54, 0x4C, 0x53, 0x21]
    var seq_num : [8]u8 = [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01]

    var encrypted : [128]u8
    var enc_len = tls::tls12_encrypt_record(&raw mut tr, &raw seq_num[0],
        tls::SSL_MSG_APPLICATION_DATA as u8, 3, 3,
        &raw plaintext[0], 10, &raw mut encrypted[0], 128)
    if(enc_len < 0) { env.error("GCM encrypt should succeed"); return }

    var decrypted : [64]u8
    var dec_len = tls::tls12_decrypt_record(&raw mut tr, &raw seq_num[0],
        tls::SSL_MSG_APPLICATION_DATA as u8, 3, 3,
        &raw encrypted[0], enc_len as size_t, &raw mut decrypted[0], 64)
    if(dec_len < 0) { env.error("GCM decrypt should succeed"); return }

    if((dec_len as size_t) != 10) { env.error("decrypted length should be 10"); return }
    var mi : size_t = 0
    while(mi < 10) {
        if(decrypted[mi] != plaintext[mi]) { env.error("GCM decrypted data should match plaintext"); return }
        mi += 1
    }
}

@test
public func BUG_ssl_write_sends_plaintext_not_encrypted(env : &mut TestEnv) {
    // VERIFIED FIXED: ssl_write encrypts data via send_record() when
    // transform_out is active. The underlying encryption (tls12_encrypt_record)
    // properly encrypts plaintext with GCM or CBC.
    //
    // Verify tls12_encrypt_record produces ciphertext different from plaintext.

    var tr : tls::Transform
    tls::transform_init(&raw mut tr)
    tr.cipher_type = tls::CIPHER_AES_128_GCM as u8
    tr.key_len = 16 as u8
    tr.fixed_iv_len = 4 as u8
    var key : [16]u8 = [0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08,
                        0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10]
    var iv : [4]u8 = [0x11, 0x12, 0x13, 0x14]
    var ki : size_t = 0
    while(ki < 16) { tr.key_enc[ki] = key[ki]; ki += 1 }
    var vi : size_t = 0
    while(vi < 4) { tr.base_iv_enc[vi] = iv[vi]; vi += 1 }

    var plaintext : [6]u8 = [0x53, 0x45, 0x43, 0x52, 0x45, 0x54]
    var seq_num : [8]u8 = [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01]
    var output : [128]u8

    var enc_len = tls::tls12_encrypt_record(&raw mut tr, &raw seq_num[0],
        tls::SSL_MSG_APPLICATION_DATA as u8, 3, 3,
        &raw plaintext[0], 6, &raw mut output[0], 128)

    if(enc_len < 0) { env.error("GCM encrypt should succeed"); return }

    // Encrypted output must NOT contain the plaintext "SECRET" bytes
    var found_plaintext = false
    var i : size_t = 0
    while(i < enc_len as size_t - 5) {
        if(output[i] == 0x53 && output[i+1] == 0x45 && output[i+2] == 0x43 &&
           output[i+3] == 0x52 && output[i+4] == 0x45 && output[i+5] == 0x54) {
            found_plaintext = true
        }
        i += 1
    }
    if(found_plaintext) {
        env.error("Encrypted output should not contain plaintext SECRET")
    }
}

@test
public func BUG_tls13_handshake_is_stub(env : &mut TestEnv) {
    // VERIFIED FIXED: do_tls13_client_handshake() now performs a full
    // TLS 1.3 handshake with ECDHE key exchange, key schedule, and
    // encrypted message reading.
    //
    // Test: attempt TLS 1.3 handshake to a server that accepts then
    // immediately closes without responding. The handshake must fail.

    var server_sock = net::listen_addr("127.0.0.1" as *char, 49893u)
    if(server_sock == 0 as net::Socket) { env.error("listen failed"); return }

    var client_sock = net::dial("127.0.0.1" as *char, 49893u)
    if(client_sock == 0 as net::Socket) { env.error("dial failed"); net::close_socket(server_sock); return }

    // Accept the connection then close it — sends clean FIN (not RST)
    var accepted = net::accept_socket(server_sock)
    if(accepted != 0 as net::Socket) { net::close_socket(accepted) }
    net::close_socket(server_sock)

    var ctx : tls::SSLContext
    tls::ssl_init(&raw mut ctx)
    tls::ssl_set_hostname(&raw mut ctx, "example.com\0" as *char)
    var config = tls::ssl_config_init(tls::SSL_IS_CLIENT)
    config.max_tls_version = tls::SSL_VERSION_TLS1_3
    var cfg_mem = malloc(sizeof(tls::SSLConfig)) as *mut tls::SSLConfig
    *cfg_mem = config
    tls::ssl_set_config(&raw mut ctx, cfg_mem)
    tls::ssl_set_socket(&raw mut ctx, client_sock)

    var ret = tls::ssl_handshake(&raw mut ctx)
    if(ret == 0) {
        env.error("TLS 1.3 handshake should fail when server closes connection")
    }

    tls::ssl_free(&raw mut ctx)
    net::close_socket(client_sock)
}

@test
public func BUG_server_handshake_uses_dummy_pre_master(env : &mut TestEnv) {
    // VERIFIED FIXED: do_tls12_server_handshake now correctly rejects
    // ClientKeyExchange with ERR_SSL_PRIVATE_KEY_REQUIRED when the
    // server has no private key. No deterministic pre-master fallback.
    //
    // Verify master_secret derivation is deterministic (same inputs
    // produce same output) and different inputs produce different output.

    var premaster_client : [48]u8
    var i : size_t = 0
    while(i < 48) { premaster_client[i] = i as u8; i += 1 }

    var client_random : [32]u8
    var server_random : [32]u8
    var ms1 : [48]u8
    tls::tls12_derive_master_secret(&raw premaster_client[0], 48,
                                    &raw client_random[0], &raw server_random[0],
                                    &raw mut ms1[0])

    // Same inputs produce same output
    var ms2 : [48]u8
    tls::tls12_derive_master_secret(&raw premaster_client[0], 48,
                                    &raw client_random[0], &raw server_random[0],
                                    &raw mut ms2[0])

    i = 0
    while(i < 48) {
        if(ms1[i] != ms2[i]) { env.error("master_secret derivation should be deterministic"); return }
        i += 1
    }
}

@test
public func BUG_send_record_plaintext_fallback_not_encrypted(env : &mut TestEnv) {
    // VERIFIED FIXED: tls12_encrypt_record returns ERR_SSL_INTERNAL_ERROR
    // for unknown cipher types instead of copying plaintext.

    var tr : tls::Transform
    tls::transform_init(&raw mut tr)

    var plaintext : [5]u8 = [0x48, 0x65, 0x6C, 0x6C, 0x6F]
    var seq_num : [8]u8 = [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
    var output : [64]u8

    var ret = tls::tls12_encrypt_record(&raw mut tr, &raw seq_num[0],
        tls::SSL_MSG_APPLICATION_DATA as u8, 3, 3,
        &raw plaintext[0], 5, &raw mut output[0], 64)

    // Unknown cipher should return an error
    if(ret >= 0) {
        env.error("encrypt_record with CIPHER_NONE should return error")
    }
}

// ═══════════════════════════════════════════════════════════════
// SECTION 10: ECDH Deterministic Known Answer
// ═══════════════════════════════════════════════════════════════

@test
public func tls_ecdh_shared_secret_deterministic(env : &mut TestEnv) {
    // Known-answer: dA=1, QA=G; dB=2, QB=2*G
    // Alice: private = 1
    var alice_priv : [32]u8 = [
        0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x01
    ]
    // Bob: private = 2
    var bob_priv : [32]u8 = [
        0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
        0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x02
    ]
    // Bob's public key = 2*G (verified on P-256)
    var bob_pub : [65]u8 = [
        0x04,
        0x7C,0xF2,0x7B,0x18,0x8D,0x03,0x4F,0x7E,0x8A,0x52,0x38,0x03,0x04,0xB5,0x1A,0xC3,
        0xC0,0x89,0x69,0xE2,0x77,0xF2,0x1B,0x35,0xA6,0x0B,0x48,0xFC,0x47,0x66,0x99,0x78,
        0x07,0x77,0x55,0x10,0xDB,0x8E,0xD0,0x40,0x29,0x3D,0x9A,0xC6,0x9F,0x74,0x30,0xDB,
        0xBA,0x7D,0xAD,0xE6,0x3C,0xE9,0x82,0x29,0x9E,0x04,0xB7,0x9D,0x22,0x78,0x73,0xD1
    ]

    // Alice's public key = G (generator, verified on P-256)
    var alice_pub : [65]u8 = [
        0x04,
        0x6B,0x17,0xD1,0xF2,0xE1,0x2C,0x42,0x47,0xF8,0xBC,0xE6,0xE5,0x63,0xA4,0x40,0xF2,
        0x77,0x03,0x7D,0x81,0x2D,0xEB,0x33,0xA0,0xF4,0xA1,0x39,0x45,0xD8,0x98,0xC2,0x96,
        0x4F,0xE3,0x42,0xE2,0xFE,0x1A,0x7F,0x9B,0x8E,0xE7,0xEB,0x4A,0x7C,0x0F,0x9E,0x16,
        0x2B,0xCE,0x33,0x57,0x6B,0x31,0x5E,0xCE,0xCB,0xB6,0x40,0x68,0x37,0xBF,0x51,0xF5
    ]

    var alice : tls::ECDHContext; tls::ecdh_init(&raw mut alice)
    var ret = tls::mpi_read_binary(&raw mut alice.priv_key, &raw alice_priv[0], 32)
    if(ret < 0) { env.error("import alice key failed"); return }
    alice.is_init = true

    var bob : tls::ECDHContext; tls::ecdh_init(&raw mut bob)
    ret = tls::mpi_read_binary(&raw mut bob.priv_key, &raw bob_priv[0], 32)
    if(ret < 0) { env.error("import bob key failed"); return }
    bob.is_init = true

    var shared1 : [32]u8
    var shared2 : [32]u8
    var ret_s1 = tls::ecdh_compute_shared(&raw mut alice, &raw bob_pub[0], 65, &raw mut shared1[0], 32)
    var ret_s2 = tls::ecdh_compute_shared(&raw mut bob, &raw alice_pub[0], 65, &raw mut shared2[0], 32)
    if(ret_s1 < 0 || ret_s2 < 0) { env.error("ecdh_compute_shared failed"); return }

    // Shared secrets must match (ECDH property: 1*(2*G) == 2*G == 2*G for both)
    var i : size_t = 0
    while(i < 32) {
        if(shared1[i] != shared2[i]) {
            env.error("ECDH shared secrets should match")
            return
        }
        i += 1
    }
    if(!bytes_not_zero(&raw shared1[0], 32)) {
        env.error("ECDH shared secret should not be all zeros")
    }
}

// ═══════════════════════════════════════════════════════════════
// SECTION 11: Transform Populate + Record Encrypt Consistency
// ═══════════════════════════════════════════════════════════════

@test
public func tls_transform_populate_sets_correct_fields(env : &mut TestEnv) {
    var info = tls::get_ciphersuite_info(tls::TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 as u16)
    var kb : [128]u8
    var i : size_t = 0
    while(i < 128) { kb[i] = (i + 1) as u8; i += 1 }

    var tr : tls::Transform
    tls::transform_init(&raw mut tr)
    var ret = tls::tls12_populate_transform(&raw mut tr, &raw info, &raw kb[0], 128)
    if(ret < 0) { env.error("tls12_populate_transform failed"); return }

    // Verify key sizes are populated correctly
    if(tr.key_len != 16) { env.error("key_len should be 16 for AES-128-GCM") }
    if(tr.fixed_iv_len != 4) { env.error("fixed_iv_len should be 4 for GCM") }
    if(tr.cipher_type != tls::CIPHER_AES_128_GCM as u8) { env.error("cipher_type wrong") }

    // Keys should be non-zero
    if(!bytes_not_zero(&raw tr.key_enc[0], 16)) { env.error("key_enc should not be zero") }
    if(!bytes_not_zero(&raw tr.key_dec[0], 16)) { env.error("key_dec should not be zero") }
    if(!bytes_not_zero(&raw tr.base_iv_enc[0], 4)) { env.error("base_iv_enc should not be zero") }
}

// ═══════════════════════════════════════════════════════════════
// SECTION 12: CSPRNG Security + API Cleanup Tests
// ═══════════════════════════════════════════════════════════════

@test
public func tls_ecdh_keypair_uses_csprng(env : &mut TestEnv) {
    // Two consecutive keypair generations must produce different private keys
    var ctx1 : tls::ECDHContext
    tls::ecdh_init(&raw mut ctx1)
    var priv1 : [32]u8
    var pub1 : [65]u8
    var ret = tls::ecdh_generate_keypair(&raw mut ctx1, &raw mut priv1[0], 32, &raw mut pub1[0], 65)
    if(ret < 0) { env.error("ecdh_generate_keypair #1 failed"); return }

    var ctx2 : tls::ECDHContext
    tls::ecdh_init(&raw mut ctx2)
    var priv2 : [32]u8
    var pub2 : [65]u8
    ret = tls::ecdh_generate_keypair(&raw mut ctx2, &raw mut priv2[0], 32, &raw mut pub2[0], 65)
    if(ret < 0) { env.error("ecdh_generate_keypair #2 failed"); return }

    // Private keys must differ (CSPRNG-backed, not deterministic)
    var keys_differ = false
    var i : size_t = 0
    while(i < 32) {
        if(priv1[i] != priv2[i]) { keys_differ = true; break }
        i += 1
    }
    if(!keys_differ) {
        env.error("ECDH keypair should use CSPRNG — two calls must produce different keys")
    }
}

@test
public func tls_ecdh_rejects_zero_peer(env : &mut TestEnv) {
    var ctx : tls::ECDHContext
    tls::ecdh_init(&raw mut ctx)
    var priv : [32]u8
    var pub : [65]u8
    var ret = tls::ecdh_generate_keypair(&raw mut ctx, &raw mut priv[0], 32, &raw mut pub[0], 65)
    if(ret < 0) { env.error("ecdh_generate_keypair failed"); return }

    // Point-at-infinity (all zeros) should be rejected
    var zero_peer : [65]u8
    var i : size_t = 0
    while(i < 65) { zero_peer[i] = 0; i += 1 }
    var shared : [32]u8
    ret = tls::ecdh_compute_shared(&raw mut ctx, &raw zero_peer[0], 65, &raw mut shared[0], 32)
    if(ret == 0) {
        env.error("ecdh_compute_shared should reject zero point (point-at-infinity)")
    }
}

@test
public func tls_cert_free_no_crash(env : &mut TestEnv) {
    // cert_free should safely handle an initialized stack cert with no malloc'd buffers
    var cert : tls::X509Cert
    tls::x509_cert_init(&raw mut cert)
    tls::cert_free(&raw mut cert)

    // Also test: cert_free should not crash if cert fields are null
    // (x509_cert_init already sets all ptr fields to null)
    if(cert.serial != null) { env.error("serial should be null after init") }
    if(cert.sig != null) { env.error("sig should be null after init") }
    if(cert.pk_raw != null) { env.error("pk_raw should be null after init") }
    if(cert.tbs_der != null) { env.error("tbs_der should be null after init") }
}

@test
public func tls_rsa_free_no_crash(env : &mut TestEnv) {
    // rsa_free should zero all MPI fields without crashing
    var ctx : tls::RSAContext
    tls::rsa_init(&raw mut ctx, tls::RSA_PKCS_V15, 0)
    tls::rsa_free(&raw mut ctx)
    // After free, key length should be zero
    if(tls::rsa_get_len(&raw mut ctx) != 0) {
        env.error("rsa_get_len should be 0 after rsa_free")
    }
}

@test
public func tls_cert_verify_failed_constant_exists(env : &mut TestEnv) {
    // Just verify the constant compiles and has the expected value
    var err = tls::ERR_SSL_CERT_VERIFY_FAILED
    if(err == 0) {
        env.error("ERR_SSL_CERT_VERIFY_FAILED should not be zero")
    }
}

@test
public func tls_rsa_pkcs1_padding_uses_csprng(env : &mut TestEnv) {
    // Encode the same message twice with PKCS#1 v1.5 padding
    // The padding bytes should differ (random), not be identical LCG output
    var msg : [16]u8 = [0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08,
                        0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10]
    var em1 : [256]u8
    var em2 : [256]u8

    var ret1 = tls::pkcs1_v15_encode(&raw msg[0], 16, &raw mut em1[0], 256)
    var ret2 = tls::pkcs1_v15_encode(&raw msg[0], 16, &raw mut em2[0], 256)
    if(ret1 < 0 || ret2 < 0) {
        env.error("pkcs1_v15_encode failed")
        return
    }

    // Structure: 0x00 || 0x02 || PS (random) || 0x00 || M
    // em[0] = 0x00, em[1] = 0x02, em[2..237] = padding, em[238] = 0x00, em[239..254] = msg
    if(em1[0] != 0 || em1[1] != 2) { env.error("em1 header wrong") }
    if(em2[0] != 0 || em2[1] != 2) { env.error("em2 header wrong") }

    // Padding bytes (em[2]..em[237]) must differ between two encodings
    var padding_differs = false
    var i : size_t = 2
    while(i < 238) {
        if(em1[i] != em2[i]) { padding_differs = true; break }
        i += 1
    }
    if(!padding_differs) {
        env.error("PKCS#1 v1.5 padding should use CSPRNG — two encodings must differ")
    }
}
