// Copyright (c) Qinetik 2024.

#define PROJECT_VERSION_MAJOR 1
#define PROJECT_VERSION_MINOR 0
#define PROJECT_VERSION_PATCH 4

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)
#define VERSION_MAJOR_STR TOSTRING(PROJECT_VERSION_MAJOR)
#define VERSION_MINOR_STR TOSTRING(PROJECT_VERSION_MINOR)
#define VERSION_PATCH_STR TOSTRING(PROJECT_VERSION_PATCH)
#define VERSION_STRING VERSION_MAJOR_STR "." VERSION_MINOR_STR "." VERSION_PATCH_STR
