name: Test Latest Release Assets

on:
  workflow_dispatch:

jobs:
  test-release:
    name: Test ${{ matrix.asset }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset: linux-x86-64-tcc.zip
            chemical_executable: chemical
            binary_name: main
          - os: ubuntu-latest
            asset: linux-x86-64.zip
            chemical_executable: chemical
            binary_name: main
          - os: windows-latest
            asset: windows-x64-tcc.zip
            chemical_executable: chemical.exe
            binary_name: main.exe
          - os: windows-latest
            asset: windows-x64.zip
            chemical_executable: chemical.exe
            binary_name: main.exe

    steps:
      - name: Create main.ch source file (Linux)
        if: runner.os != 'Windows'
        run: |
          echo "public func printf(format : *char, _ : any...)" > main.ch
          echo "public func main() : int {" >> main.ch
          echo "    printf(\"hello world\")" >> main.ch
          echo "    return 0;" >> main.ch
          echo "}" >> main.ch
        shell: bash

      - name: Create main.ch source file (Windows)
        if: runner.os == 'Windows'
        run: |
          Set-Content -Path main.ch -Value @(
            'public func printf(format : *char, _ : any...)',
            'public func main() : int {',
            '    printf("hello world")',
            '    return 0;',
            '}'
          )
        shell: pwsh

      - name: Download release asset (Linux)
        if: runner.os != 'Windows'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching release information (including pre-releases)..."
          releases=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases")
          ASSET_URL=$(echo "$releases" | jq -r '[.[] | select(.assets | map(.name) | index("${{ matrix.asset }}"))] | .[0].assets[] | select(.name=="${{ matrix.asset }}") | .browser_download_url')
          if [ -z "$ASSET_URL" ] || [ "$ASSET_URL" = "null" ]; then
            echo "Error: Asset ${{ matrix.asset }} not found in any release."
            exit 1
          fi
          echo "Downloading asset from $ASSET_URL"
          curl -L -o asset.zip "$ASSET_URL"
        shell: bash

      - name: Download release asset (Windows)
        if: runner.os == 'Windows'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Write-Host "Fetching release information (including pre-releases)..."
          $releases = Invoke-RestMethod -Uri "https://api.github.com/repos/${env:GITHUB_REPOSITORY}/releases" -Headers @{ Authorization = "token $env:GITHUB_TOKEN" }
          $assetName = "${{ matrix.asset }}"
          $release = $releases | Where-Object { $_.assets -and ($_.assets | Where-Object { $_.name -eq $assetName }) } | Select-Object -First 1
          if (-not $release) {
            Write-Error "Error: Asset $assetName not found in any release."
            exit 1
          }
          $asset = $release.assets | Where-Object { $_.name -eq $assetName }
          if (-not $asset) {
            Write-Error "Error: Asset $assetName not found in the selected release."
            exit 1
          }
          Write-Host "Downloading asset from $($asset.browser_download_url)"
          Invoke-WebRequest -Uri $asset.browser_download_url -OutFile asset.zip
        shell: pwsh

      - name: Extract asset (Linux)
        if: runner.os != 'Windows'
        run: |
          unzip -o -q asset.zip || true
        shell: bash

      - name: Extract asset (Windows)
        if: runner.os == 'Windows'
        run: |
          Expand-Archive -Path asset.zip -DestinationPath .
        shell: pwsh

      - name: Compile source code (Linux)
        if: runner.os != 'Windows'
        run: |
          # Find the folder where the compiler executable resides.
          folder="."
          if [ ! -f "./${{ matrix.chemical_executable }}" ]; then
            folder=$(dirname "$(find . -type f -name "${{ matrix.chemical_executable }}" | head -n 1)")
          fi
          echo "Using folder: $folder"
          # Copy the source file into that folder.
          cp main.ch "$folder/"
          pushd "$folder"
          ./${{ matrix.chemical_executable }} main.ch -o ${{ matrix.binary_name }} -v
          popd
        shell: bash

      - name: Compile source code (Windows)
        if: runner.os == 'Windows'
        run: |
          $folder = "."
          if (!(Test-Path -Path ".\${{ matrix.chemical_executable }}")) {
            $found = Get-ChildItem -Path . -Recurse -Filter "${{ matrix.chemical_executable }}" -File | Select-Object -First 1
            if ($found) {
              $folder = Split-Path $found.FullName -Parent
            }
          }
          Write-Host "Using folder: $folder"
          Copy-Item -Path main.ch -Destination $folder
          Push-Location $folder
          .\${{ matrix.chemical_executable }} main.ch -o ${{ matrix.binary_name }} -v
          Pop-Location
        shell: pwsh

      - name: Run compiled program and capture output (Linux)
        if: runner.os != 'Windows'
        run: |
          folder="."
          if [ ! -f "./${{ matrix.chemical_executable }}" ]; then
            folder=$(dirname "$(find . -type f -name "${{ matrix.chemical_executable }}" | head -n 1)")
          fi
          echo "Using folder: $folder"
          pushd "$folder"
          ./${{ matrix.binary_name }} | tee output.txt
          popd
          cp "$folder/output.txt" .
        shell: bash

      - name: Run compiled program and capture output (Windows)
        if: runner.os == 'Windows'
        run: |
          $folder = "."
          if (!(Test-Path -Path ".\${{ matrix.chemical_executable }}")) {
            $found = Get-ChildItem -Path . -Recurse -Filter "${{ matrix.chemical_executable }}" -File | Select-Object -First 1
            if ($found) {
              $folder = Split-Path $found.FullName -Parent
            }
          }
          Write-Host "Using folder: $folder"
          Push-Location $folder
          .\${{ matrix.binary_name }} | Tee-Object -FilePath output.txt
          Pop-Location
          Copy-Item -Path "$folder\output.txt" -Destination "$env:GITHUB_WORKSPACE\output.txt"
        shell: pwsh

      - name: Upload output artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset }}-output
          path: output.txt
